### ISSUE TITLE
Cannot decrypt if key is shorter than expected

### ISSUE THREAD

**Issue by adrianlzt** [Telefonica/vaultier-cli#37]
I have seen this base64 workspace_key in one workspace created by the web client.
```
z9fmulUNFMIVfezqONdVBWdBDiMeD/Jun2g8TX3iR+k2LbdW4b4YE9n/5vqvDfUQnDfw2P3+aM0HbXCHCmfUMYZs5QRf1q+8blFh0ya78498QU+UGdhWLrEQu2OseDNuMfVqNSwUkNZUvXB0oIPvA3JUspjyLg9sCz2VZ2jIry+ocN12meqibRLdHFqJiD9NuP/zUbs7+bTbSj87UItsQIPn94RT4OD6KBcTMKWIa/rc1dZqDPBM5082N8GpH2snc3Kpahe3nbVpnX+7vJPF6vfJUaE7NwPTKUI3mOpOEPNb86LrmPg2/RsF32Sz6bgISVLJsZywmLNMz5X4jKXG
```

When vaultcli tries to use it to initilize the decrypter it fails:
```
Traceback (most recent call last):
  File "/home/adrian/Documentos/TD-Soporte/dsn/vaultier-cli/vaultcli/workspacecypher.py", line 54, in decrypt
    decrypted = self.priv.decrypt(raw_cipher_data,'')
  File "/home/adrian/.virtualenvs/vaultier/lib/python3.6/site-packages/pycryptodomex-3.4.5-py3.6-linux-x86_64.egg/Cryptodome/Cipher/PKCS1_v1_5.py", line 207, in decrypt
    raise ValueError("Ciphertext with incorrect length.")
ValueError: Ciphertext with incorrect length.
```

Others workspaces have a base64 workspace key size of 344, this one is 340.

We should fix our cli so it can handle this strange shorter keys.

**Comment by adrianlzt** [comment]
Make a test with this value.
